// Sprite sheet: one picture per pose, with its size on the original sheet (w x h px).
const S = {
  "g_idle": {"src": "assets/sprites/g_idle.png", "w": 98, "h": 163},
  "g_down": {"src": "assets/sprites/g_down.png", "w": 97, "h": 162},
  "g_left": {"src": "assets/sprites/g_left.png", "w": 89, "h": 163},
  "g_right": {"src": "assets/sprites/g_right.png", "w": 92, "h": 165},
  "g_up": {"src": "assets/sprites/g_up.png", "w": 94, "h": 172},
  "g_wave": {"src": "assets/sprites/g_wave.png", "w": 106, "h": 157},
  "g_happy": {"src": "assets/sprites/g_happy.png", "w": 99, "h": 158},
  "g_shy": {"src": "assets/sprites/g_shy.png", "w": 96, "h": 157},
  "g_sit": {"src": "assets/sprites/g_sit.png", "w": 98, "h": 140},
  "b_idle": {"src": "assets/sprites/b_idle.png", "w": 85, "h": 172},
  "b_down": {"src": "assets/sprites/b_down.png", "w": 85, "h": 175},
  "b_left": {"src": "assets/sprites/b_left.png", "w": 87, "h": 175},
  "b_right": {"src": "assets/sprites/b_right.png", "w": 87, "h": 175},
  "b_up": {"src": "assets/sprites/b_up.png", "w": 82, "h": 179},
  "b_wave": {"src": "assets/sprites/b_wave.png", "w": 105, "h": 168},
  "b_happy": {"src": "assets/sprites/b_happy.png", "w": 90, "h": 168},
  "b_shy": {"src": "assets/sprites/b_shy.png", "w": 88, "h": 167},
  "b_sit": {"src": "assets/sprites/b_sit.png", "w": 101, "h": 150},
  "g_type": {"src": "assets/sprites/g_type.png", "w": 115, "h": 144},
  "b_type": {"src": "assets/sprites/b_type.png", "w": 99, "h": 152},
  "stand": {"src": "assets/sprites/stand.png", "w": 133, "h": 152},
  "hands": {"src": "assets/sprites/hands.png", "w": 137, "h": 148},
  "hug": {"src": "assets/sprites/hug.png", "w": 111, "h": 144},
  "kiss": {"src": "assets/sprites/kiss.png", "w": 128, "h": 139},
  "sit": {"src": "assets/sprites/sit.png", "w": 182, "h": 142},
  "lap": {"src": "assets/sprites/lap.png", "w": 206, "h": 135},
  "feed": {"src": "assets/sprites/feed.png", "w": 158, "h": 135},
  "boop": {"src": "assets/sprites/boop.png", "w": 165, "h": 143},
  "play": {"src": "assets/sprites/play.png", "w": 183, "h": 130},
  "cuddle": {"src": "assets/sprites/cuddle.png", "w": 211, "h": 123},
  "sleep": {"src": "assets/sprites/sleep.png", "w": 190, "h": 110},
  "look": {"src": "assets/sprites/look.png", "w": 164, "h": 126},
  "talk": {"src": "assets/sprites/talk.png", "w": 163, "h": 130},
  "photo": {"src": "assets/sprites/photo.png", "w": 159, "h": 126},
  "cat_sit": {"src": "assets/sprites/cat_sit.png", "w": 68, "h": 78},
  "cat_happy": {"src": "assets/sprites/cat_happy.png", "w": 68, "h": 78},
  "cat_sleep": {"src": "assets/sprites/cat_sleep.png", "w": 88, "h": 46},
  "cat_r1": {"src": "assets/sprites/cat_r1.png", "w": 108, "h": 72},
  "cat_r2": {"src": "assets/sprites/cat_r2.png", "w": 108, "h": 72},
  "cat_l1": {"src": "assets/sprites/cat_l1.png", "w": 108, "h": 72},
  "cat_l2": {"src": "assets/sprites/cat_l2.png", "w": 108, "h": 72}
};
const BG = "assets/bg.webp";
